# Array Attributes

In [69]:
import numpy as np 

In [10]:
x=np.zeros((3,4,5),dtype='int64')
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
3
(3, 4, 5)
60
int64


# Array Indexing

In [11]:
x1=np.array([5,0,3,3,7,9])
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
print(x1[0])
print(x1[-1])
print(x1[-2])

5
9
7


In [16]:
x2=np.array([[3,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
print(x2[0,0])
print(x2[2,-1])
x2[0,0]=5
print(x2)

5
7
[[5 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


# Array Slicing

In [19]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(x[1:5])
print(x[:3])
print(x[5:])
print(x[::-2])
print(x[5::-1])

[1 2 3 4]
[0 1 2]
[5 6 7 8 9]
[9 7 5 3 1]
[5 4 3 2 1 0]


# Slicing in Multi-dimensional Arrays


In [30]:
x2=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
print(x2[0:2,2:3])
print(x2[:2,:3])
print(x2[:3,::2])
print(x2[1:,3:])
print(x2[::-1,::-1])

[[2]
 [8]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[[8]
 [7]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


# Copying Arrays

In [33]:
x2=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [34]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [35]:
x2_sub[0,0]=99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Creating copies of arrays


In [36]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [37]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshape Arrays

In [39]:
grid=np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
grid=np.arange(0,12).reshape((6,2))
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [41]:
grid.reshape((2,-1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# Concatenate Arrays

In [42]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [43]:
z=np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [44]:
x=np.full((2,3),1)
y=np.full((2,3),9)
print(x)
print(y)
np.concatenate([x,y],axis=0)

[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [45]:
np.concatenate([x,y],axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [49]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
x=x.reshape((1,-1))
np.concatenate([x,grid],axis=0)
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [50]:
grid=np.array([[9,8,7],[6,5,4]])
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Split Arrays

In [51]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [52]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [54]:
upper,lower=np.hsplit(grid,[2])
print(upper)
print(lower)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Universal Functions 1


In [55]:
np.random.seed(0)
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range (len(values)):
        output[i]=1.0/values[i]
    return output
values=np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [56]:
big_array=np.random.randint(1,100,size=100000)
%timeit compute_reciprocals(big_array)

387 ms ± 3.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [57]:
print(compute_reciprocals(values))
print(1./values)
big_array=np.random.randint(1,100,size=100000)
%timeit 1./big_array

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]
267 µs ± 2.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Universal Functions 2


In [88]:
from scipy import special

In [89]:
x=[1,5,10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [92]:
x=np.array([0,0.3,0.7,1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))


[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]
