In [2]:
import numpy as np

# The Basics

In [3]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


In [5]:
#get dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
#get type
print(a.dtype)
print(b.dtype)

int32
float64


In [13]:
#get size
print(a.size)
print(b.size)

3
6


In [12]:
#get item size
print(a.itemsize)
print(b.itemsize)

4
8


In [14]:
#get total size
print(a.size * a.itemsize)
print(b.size * b.itemsize)

12
48


In [15]:
#get total size (another solution)
print(a.nbytes)
print(b.nbytes)

12
48


# Accessing/changing specific elements,row,columns,ect

In [16]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [19]:
#get a specific element [r,c]
print(a[1,5])

13


In [20]:
#get a specific row 
print (a[0,:])

[1 2 3 4 5 6 7]


In [24]:
#get a specific column 
print (a[:,2])

[ 3 10]


In [25]:
#getting a little more fancy [startindex:endindex:stepsize]
print (a[0,1:6:2])

[2 4 6]


In [26]:
#changing element
a[1,5]=25
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 25 14]]


In [6]:
#changing element
a[:,2]=[30,100]
print(a)

NameError: name 'a' is not defined

# 3-d array (example)

In [36]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,'\n\n')
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 


(2, 2, 2)


In [37]:
#get specific element
print (b[0,1,1],'\n\n')
print (b[:,1,:])

4 


[[3 4]
 [7 8]]


In [38]:
#Replace
b[:,1,:]=[[9,9],[8,8]]
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# different types of arrays

In [9]:
#All 0s matrix
print(np.zeros (5),'\n\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.] 


[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#All 1s matrix
print(np.ones((3,2)) ,'\n\n')
print(np.ones((2,3,4)))

[[1. 1.]
 [1. 1.]
 [1. 1.]] 


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
#Any other number
print(np.full((3,2),9) ,'\n\n')
print(np.full((2,3,4),5))

[[9 9]
 [9 9]
 [9 9]] 


[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [3]:
#any other number (full_like)
print(np.full(a.shape,4),'\n\n')
#or


NameError: name 'a' is not defined

In [4]:
#Random decimal numbers
print(np.random.rand(3,6))

[[0.2208243  0.7521171  0.93321156 0.50944924 0.74465766 0.34209071]
 [0.89364812 0.39579715 0.16764666 0.84615022 0.14128214 0.15976021]
 [0.51155348 0.92463147 0.11576178 0.04450762 0.48947295 0.02469476]]


In [5]:
#Random integer numbers
print(np.random.randint(5,size=(3,6)),'\n\n')
print(np.random.randint(2,6,size=(3,6)))

[[1 0 0 3 4 2]
 [4 4 0 4 2 4]
 [2 0 4 1 4 2]] 


[[4 2 4 3 2 4]
 [4 3 2 4 3 2]
 [3 2 4 5 2 5]]


In [30]:
#the identity matrix
print(np.identity(5),'\n\n')
print(np.identity(3))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
#Repeat an array
array=np.array([[1,2,3]])
r=np.repeat(array,3)
e=np.repeat(array,3, axis=0)
print(array,'\n\n')
print(r,'\n\n')
print(e)

[[1 2 3]] 


[1 1 1 2 2 2 3 3 3] 


[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Mathematics

In [65]:
m=np.array([1,2,3,4,5])
print(m,'\n\n')
print(m+2,'\n\n')
print(m-2,'\n\n')
print(m*2,'\n\n')
print(m/2,'\n\n')
print(m**2)

[1 2 3 4 5] 


[3 4 5 6 7] 


[-1  0  1  2  3] 


[ 2  4  6  8 10] 


[0.5 1.  1.5 2.  2.5] 


[ 1  4  9 16 25]


In [67]:
m += 2
print(m)

[5 6 7 8 9]


In [69]:
b=np.array([2,4,6,8,10])
print(b,'\n\n')
print(m+b)


[ 2  4  6  8 10] 


[ 7 10 13 16 19]


In [72]:
#take the (sin,cos,tan)
print(np.sin(m))
print(np.cos(m))
print(np.tan(m),'\n\n')
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))


[-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
[-3.38051501 -0.29100619  0.87144798 -6.79971146 -0.45231566] 


[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153]
[-2.18503986  1.15782128 -0.29100619 -6.79971146  0.64836083]
