In [9]:
import numpy as np

In [11]:
x=np.array([[174,  96,   4],
       [195, 104,   3],
       [147,  92,   5],
       [169, 103,   4],
       [192, 101,   3],
       [153, 107,   5],
       [144, 145,   5],
       [153, 149,   5],
       [172,  67,   2],
       [187,  62,   1],
       [153, 121,   5],
       [160, 131,   5],
       [197, 114,   3],
       [185,  81,   2],
       [157,  56,   2],
       [185,  76,   2],
       [161,  72,   3],
       [176,  54,   1],
       [196, 116,   4],
       [178, 127,   5],
       [191,  54,   0],
       [190,  83,   2],
       [172,  96,   4],
       [194, 136,   4],
       [141,  80,   5],
       [197, 154,   4],
       [176, 122,   4],
       [166, 140,   5],
       [168, 123,   5],
       [145, 117,   5],
       [178, 154,   5],
       [177,  61,   2],
       [142,  69,   4],
       [190,  50,   0],
       [161, 155,   5],
       [195, 126,   4],
       [181, 106,   4],
       [146, 157,   5],
       [177,  96,   4],
       [146, 104,   5],
       [168,  87,   4],
       [184, 160,   5],
       [194, 115,   4],
       [154,  54,   2],
       [158, 153,   5],
       [183, 150,   5],
       [171, 147,   5],
       [167,  85,   4],
       [140,  79,   5],
       [140, 146,   5],
       [196,  50,   0],
       [168, 140,   5],
       [182,  84,   3],
       [181, 105,   4],
       [192, 101,   3],
       [181,  78,   2],
       [151,  67,   3],
       [174, 138,   5],
       [197, 149,   4],
       [181,  94,   3],
       [162,  74,   3],
       [180,  73,   2],
       [167, 135,   5],
       [158,  95,   4],
       [165, 105,   4],
       [145, 108,   5],
       [166, 144,   5],
       [179,  93,   3],
       [145, 160,   5],
       [196, 122,   4],
       [150,  84,   4],
       [196, 159,   5],
       [143, 118,   5],
       [159, 109,   5],
       [152,  90,   4],
       [155, 144,   5],
       [171, 120,   5],
       [153,  78,   2],
       [145,  78,   4],
       [165, 155,   5],
       [178,  85,   3],
       [177, 155,   5],
       [182,  98,   3],
       [161,  89,   4],
       [169, 141,   5],
       [162,  58,   2],
       [169, 145,   5],
       [163, 131,   5],
       [147,  84,   4],
       [154, 145,   5],
       [145, 130,   5],
       [163,  57,   0],
       [179, 114,   4],
       [188,  57,   1],
       [147,  94,   5],
       [181, 139,   4],
       [156,  52,   2],
       [183, 105,   3],
       [168, 143,   5],
       [140,  76,   4],
       [186, 140,   5],
       [179, 110,   4],
       [183, 153,   5],
       [171, 141,   5],
       [191, 146,   5],
       [154, 132,   5],
       [170,  95,   4],
       [181, 111,   4],
       [144,  66,   4],
       [167,  85,   4],
       [164, 160,   5],
       [172,  62,   2],
       [167, 153,   5],
       [161, 145,   5],
       [154,  92,   4],
       [184, 106,   4],
       [178, 138,   5],
       [197,  88,   2],
       [190,  50,   0],
       [186, 143,   5],
       [193,  61,   1],
       [195, 147,   4],
       [185,  94,   3],
       [147,  67,   4],
       [185,  60,   1],
       [150, 144,   5],
       [154,  96,   5],
       [191,  62,   1],
       [182, 149,   5],
       [160,  83,   4],
       [167,  58,   2],
       [183,  87,   3],
       [187,  96,   3],
       [163, 137,   5],
       [182,  70,   2],
       [148, 141,   5],
       [146, 123,   5],
       [177, 101,   4],
       [157, 103,   5],
       [162,  64,   2],
       [195,  61,   1],
       [178, 107,   4],
       [188, 141,   4],
       [165,  95,   4],
       [150,  97,   5],
       [168, 158,   5],
       [188,  65,   1],
       [182,  73,   2],
       [186, 128,   4],
       [176, 121,   4],
       [162, 157,   5],
       [182,  50,   0],
       [188, 128,   4],
       [184, 147,   5],
       [179,  56,   1],
       [158, 127,   5],
       [161, 115,   5],
       [154, 112,   5],
       [167,  79,   3],
       [167,  64,   2],
       [155, 115,   5],
       [146,  85,   4],
       [160, 109,   5],
       [179, 150,   5],
       [198,  50,   0],
       [150, 153,   5],
       [150,  95,   5]])

In [13]:
## 1- Find the number of dimensions, the size and the shape of this array
print("Dimesions =",x.ndim)
print("size =",x.size)
print("shape =",x.shape)

Dimesions = 2
size = 501
shape = (167, 3)


In [15]:
#2-what is data type
print("data type =",x.dtype )

data type = int32


In [22]:
#3-Extract every 3 rows
x1=x[::3,:]
print(x1)

[[174  96   4]
 [169 103   4]
 [144 145   5]
 [187  62   1]
 [197 114   3]
 [185  76   2]
 [196 116   4]
 [190  83   2]
 [141  80   5]
 [166 140   5]
 [178 154   5]
 [190  50   0]
 [181 106   4]
 [146 104   5]
 [194 115   4]
 [183 150   5]
 [140  79   5]
 [168 140   5]
 [192 101   3]
 [174 138   5]
 [162  74   3]
 [158  95   4]
 [166 144   5]
 [196 122   4]
 [143 118   5]
 [155 144   5]
 [145  78   4]
 [177 155   5]
 [169 141   5]
 [163 131   5]
 [145 130   5]
 [188  57   1]
 [156  52   2]
 [140  76   4]
 [183 153   5]
 [154 132   5]
 [144  66   4]
 [172  62   2]
 [154  92   4]
 [197  88   2]
 [193  61   1]
 [147  67   4]
 [154  96   5]
 [160  83   4]
 [187  96   3]
 [148 141   5]
 [157 103   5]
 [178 107   4]
 [150  97   5]
 [182  73   2]
 [162 157   5]
 [184 147   5]
 [161 115   5]
 [167  64   2]
 [160 109   5]
 [150 153   5]]


In [24]:
#4-extract the firt and the last in one array
x2=x1[:,::2]
x2

array([[174,   4],
       [169,   4],
       [144,   5],
       [187,   1],
       [197,   3],
       [185,   2],
       [196,   4],
       [190,   2],
       [141,   5],
       [166,   5],
       [178,   5],
       [190,   0],
       [181,   4],
       [146,   5],
       [194,   4],
       [183,   5],
       [140,   5],
       [168,   5],
       [192,   3],
       [174,   5],
       [162,   3],
       [158,   4],
       [166,   5],
       [196,   4],
       [143,   5],
       [155,   5],
       [145,   4],
       [177,   5],
       [169,   5],
       [163,   5],
       [145,   5],
       [188,   1],
       [156,   2],
       [140,   4],
       [183,   5],
       [154,   5],
       [144,   4],
       [172,   2],
       [154,   4],
       [197,   2],
       [193,   1],
       [147,   4],
       [154,   5],
       [160,   4],
       [187,   3],
       [148,   5],
       [157,   5],
       [178,   4],
       [150,   5],
       [182,   2],
       [162,   5],
       [184,   5],
       [161,

In [25]:
#5-reverse the array
x3= x[::-1,::-1]
x3

array([[  5,  95, 150],
       [  5, 153, 150],
       [  0,  50, 198],
       [  5, 150, 179],
       [  5, 109, 160],
       [  4,  85, 146],
       [  5, 115, 155],
       [  2,  64, 167],
       [  3,  79, 167],
       [  5, 112, 154],
       [  5, 115, 161],
       [  5, 127, 158],
       [  1,  56, 179],
       [  5, 147, 184],
       [  4, 128, 188],
       [  0,  50, 182],
       [  5, 157, 162],
       [  4, 121, 176],
       [  4, 128, 186],
       [  2,  73, 182],
       [  1,  65, 188],
       [  5, 158, 168],
       [  5,  97, 150],
       [  4,  95, 165],
       [  4, 141, 188],
       [  4, 107, 178],
       [  1,  61, 195],
       [  2,  64, 162],
       [  5, 103, 157],
       [  4, 101, 177],
       [  5, 123, 146],
       [  5, 141, 148],
       [  2,  70, 182],
       [  5, 137, 163],
       [  3,  96, 187],
       [  3,  87, 183],
       [  2,  58, 167],
       [  4,  83, 160],
       [  5, 149, 182],
       [  1,  62, 191],
       [  5,  96, 154],
       [  5, 144

In [28]:
#6-what is the max and min in first column
x4=x[:,0:1]

np.min(x4)

140

In [27]:
np.max(x4)

198

In [29]:
#7-find the mean and stander deviation for first column
x5=x[:,0:1]
np.mean(x5)

170.07185628742516

In [34]:
std = np.std(x5)
std

16.2931854026821

In [33]:
mean = np.sum(x5)/x5.size#mean 
mean

170.07185628742516

In [32]:
# 7- Find the 25th, 75th percentile and the median for first column
np.percentile(x4, [25,50,75])

array([156.5, 169. , 183. ])

In [35]:
# 8- Normalize first column
normalized= (x4 - mean) / std
normalized

array([[ 0.24109121],
       [ 1.52997361],
       [-1.41604332],
       [-0.06578556],
       [ 1.34584755],
       [-1.0477912 ],
       [-1.60016937],
       [-1.0477912 ],
       [ 0.1183405 ],
       [ 1.03897079],
       [-1.0477912 ],
       [-0.61816373],
       [ 1.65272432],
       [ 0.91622008],
       [-0.80228979],
       [ 0.91622008],
       [-0.55678838],
       [ 0.36384191],
       [ 1.59134896],
       [ 0.48659262],
       [ 1.2844722 ],
       [ 1.22309685],
       [ 0.1183405 ],
       [ 1.46859826],
       [-1.78429543],
       [ 1.65272432],
       [ 0.36384191],
       [-0.24991162],
       [-0.12716091],
       [-1.53879402],
       [ 0.48659262],
       [ 0.42521726],
       [-1.72292008],
       [ 1.22309685],
       [-0.55678838],
       [ 1.52997361],
       [ 0.67071867],
       [-1.47741867],
       [ 0.42521726],
       [-1.47741867],
       [-0.12716091],
       [ 0.85484473],
       [ 1.46859826],
       [-0.98641585],
       [-0.74091444],
       [ 0

In [38]:
#9-make first column row vector
x7=x4.reshape((1,-1))
x7

array([[174, 195, 147, 169, 192, 153, 144, 153, 172, 187, 153, 160, 197,
        185, 157, 185, 161, 176, 196, 178, 191, 190, 172, 194, 141, 197,
        176, 166, 168, 145, 178, 177, 142, 190, 161, 195, 181, 146, 177,
        146, 168, 184, 194, 154, 158, 183, 171, 167, 140, 140, 196, 168,
        182, 181, 192, 181, 151, 174, 197, 181, 162, 180, 167, 158, 165,
        145, 166, 179, 145, 196, 150, 196, 143, 159, 152, 155, 171, 153,
        145, 165, 178, 177, 182, 161, 169, 162, 169, 163, 147, 154, 145,
        163, 179, 188, 147, 181, 156, 183, 168, 140, 186, 179, 183, 171,
        191, 154, 170, 181, 144, 167, 164, 172, 167, 161, 154, 184, 178,
        197, 190, 186, 193, 195, 185, 147, 185, 150, 154, 191, 182, 160,
        167, 183, 187, 163, 182, 148, 146, 177, 157, 162, 195, 178, 188,
        165, 150, 168, 188, 182, 186, 176, 162, 182, 188, 184, 179, 158,
        161, 154, 167, 167, 155, 146, 160, 179, 198, 150, 150]])