In [27]:
import pandas as pd
import numpy as np

# series create, manipulate, querry, delet

In [47]:
#creating a series from a list
arr=[0,1,2,3,4]
s1=pd.Series(arr)
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [35]:
#name series
s1.name=('number')
print(s1,'\n\n')
order=[1,2,3,4,5]
s2=pd.Series(arr, index = order)
print(s2)

0    0
1    1
2    2
3    3
4    4
Name: number, dtype: int64 


1    0
2    1
3    2
4    3
5    4
dtype: int64


In [37]:
#create a random Ndarray
n=np.random.randn(5)
print(n,'\n\n')

index=['a','b','c','d','e']
s2=pd.Series(n,index=index)
print(s2)


[-1.036032    1.71889449  0.78366189 -0.83530264 -1.19754936] 


a   -1.036032
b    1.718894
c    0.783662
d   -0.835303
e   -1.197549
dtype: float64


In [38]:
#create series from dictionary
d={'a':1,'b':2,'c':3,'d':4,'e':5}
s3=pd.Series(d)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [49]:
#you can modify the index of series
print(s1,'\n\n')

s1.index=['A','B','C','D','E']
print(s1)


0    0
1    1
2    2
3    3
4    4
dtype: int64 


A    0
B    1
C    2
D    3
E    4
dtype: int64


In [52]:
#slicing
a=s1[:3]
print(a,'\n\n')
#or
print(s1[:3])

A    0
B    1
C    2
dtype: int64 


A    0
B    1
C    2
dtype: int64


In [55]:
#append
s4=s1.append(s3)
print(s4)

A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [57]:
#drop
print(s4.drop('e'))

A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
dtype: int64


# Series operations

In [59]:
arr1=[0,1,2,3,4,5,6,7]
arr2=[6,7,8,9,5]

s5=pd.Series(arr2)
s6=pd.Series(arr1)

print(s5,'\n\n')
print(s6)


0    6
1    7
2    8
3    9
4    5
dtype: int64 


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int64


In [60]:
#addition
print(s5.add(s6))

0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
7     NaN
dtype: float64


In [61]:
#subtraction
print(s5.sub(s6))

0    6.0
1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    NaN
7    NaN
dtype: float64


In [62]:
#multiplication
print(s5.mul(s6))

0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
7     NaN
dtype: float64


In [63]:
#division
print(s5.div(s6))

0     inf
1    7.00
2    4.00
3    3.00
4    1.25
5     NaN
6     NaN
7     NaN
dtype: float64


In [64]:
#med , max , min
print('median s5 = ',s5.median())
print('max s5 = ',s5.max())
print('min s5 = ',s5.min(),'\n\n')
print('median s6 = ',s6.median())
print('max s6 = ',s6.max())
print('min s6 = ',s6.min())


median s5 =  7.0
max s5 =  9
min s5 =  5 


median s6 =  3.5
max s6 =  7
min s6 =  0


# Create Dataframe

In [73]:
#Define time sequence as index
dates= pd.date_range('today',periods=6)
print(dates)

DatetimeIndex(['2022-02-19 23:36:20.151747', '2022-02-20 23:36:20.151747',
               '2022-02-21 23:36:20.151747', '2022-02-22 23:36:20.151747',
               '2022-02-23 23:36:20.151747', '2022-02-24 23:36:20.151747'],
              dtype='datetime64[ns]', freq='D')


In [74]:
#import numpy random array
num_arr=np.random.randn(6,4)
print(num_arr)

[[ 1.09194628  1.71133194 -1.81794799 -3.23000705]
 [-2.36417229  1.42848321  0.50933581 -0.01214419]
 [ 1.24033778  1.65461832  0.86915908  1.4656057 ]
 [ 1.03081954  1.51079917  0.83702379 -0.52027718]
 [ 0.90800172  1.96984894 -0.75641583  0.2878306 ]
 [-0.41127561 -0.92732145  0.90438451  0.12216186]]


In [75]:
#use the table as the column name
columns=['A','B','C','D']
print(columns)

['A', 'B', 'C', 'D']


In [80]:
#Dataframe
df1=pd.DataFrame(num_arr, index=dates , columns=columns)
df1

A         B         C         D
2022-02-19 23:36:20.151747  1.091946  1.711332 -1.817948 -3.230007
2022-02-20 23:36:20.151747 -2.364172  1.428483  0.509336 -0.012144
2022-02-21 23:36:20.151747  1.240338  1.654618  0.869159  1.465606
2022-02-22 23:36:20.151747  1.030820  1.510799  0.837024 -0.520277
2022-02-23 23:36:20.151747  0.908002  1.969849 -0.756416  0.287831
2022-02-24 23:36:20.151747 -0.411276 -0.927321  0.904385  0.122162

In [98]:
#create dataframe with dictionary array
data={'animal':['cat','cat','snake','dog','dog','cat','snake','cat','dog','dog'],
      'age':[2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3],
      'visits':[1,3,2,3,2,3,1,1,2,1],
     'priority':['yes','yes','no','yes','no','no','no','yes','no','no']}

labels=['a','b','c','d','e','f','g','h','i','j']

df2=pd.DataFrame(data, index=labels)
df2

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [82]:
#see data types of array
df2.dtypes

animal       object
age         float64
visits        int64
priority     object
dtype: object

In [84]:
df2.head()

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no

In [85]:
df2.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [87]:
df3=df2.head(6)
df3

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no

In [88]:
df2.tail()

animal  age  visits priority
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [89]:
df2.tail(4)

animal  age  visits priority
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [90]:
df2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [91]:
df2.columns

Index(['animal', 'age', 'visits', 'priority'], dtype='object')

In [92]:
df2.values

array([['cat', 2.5, 1, 'yes'],
       ['cat', 3.0, 3, 'yes'],
       ['snake', 0.5, 2, 'no'],
       ['dog', nan, 3, 'yes'],
       ['dog', 5.0, 2, 'no'],
       ['cat', 2.0, 3, 'no'],
       ['snake', 4.5, 1, 'no'],
       ['cat', nan, 1, 'yes'],
       ['dog', 7.0, 2, 'no'],
       ['dog', 3.0, 1, 'no']], dtype=object)

In [93]:
#see statical data of dataframe
df2.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [94]:
#(للتبديل)تحويل الصف لعمود والعمود لصف
df2.T

a    b      c    d    e    f      g    h    i    j
animal    cat  cat  snake  dog  dog  cat  snake  cat  dog  dog
age       2.5  3.0    0.5  NaN  5.0  2.0    4.5  NaN  7.0  3.0
visits      1    3      2    3    2    3      1    1    2    1
priority  yes  yes     no  yes   no   no     no  yes   no   no

In [95]:
df2.sort_values(by='age')

animal  age  visits priority
c  snake  0.5       2       no
f    cat  2.0       3       no
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
e    dog  5.0       2       no
i    dog  7.0       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [96]:
#slicing dataframe
df2[1:3]

animal  age  visits priority
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [99]:
df2.sort_values(by='age')[1:3]

animal  age  visits priority
f    cat  2.0       3       no
a    cat  2.5       1      yes

In [100]:
#query dataframe by tag
df2[['age','visits']]

age  visits
a  2.5       1
b  3.0       3
c  0.5       2
d  NaN       3
e  5.0       2
f  2.0       3
g  4.5       1
h  NaN       1
i  7.0       2
j  3.0       1

In [101]:
#query row 2,3
df2.iloc[1:3]

animal  age  visits priority
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [102]:
#copy
df3=df2.copy()
df3

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [103]:
#معرفة اماكن القيم الخالية(الفارغة)
df3.isnull()

animal    age  visits  priority
a   False  False   False     False
b   False  False   False     False
c   False  False   False     False
d   False   True   False     False
e   False  False   False     False
f   False  False   False     False
g   False  False   False     False
h   False   True   False     False
i   False  False   False     False
j   False  False   False     False

In [104]:
df3.loc['f','age']=1.5
df3

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [110]:
df3[['age']].mean()

age    3.375
dtype: float64

In [111]:
df3['visits'].sum()

19

In [112]:
df3.sum()

animal      catcatsnakedogdogcatsnakecatdogdog
age                                       27.0
visits                                      19
priority              yesyesnoyesnononoyesnono
dtype: object

In [113]:
df3.max()

animal      snake
age           7.0
visits          3
priority      yes
dtype: object

In [114]:
string=pd.Series(['A','C','D','Aaa','BaCa',np.nan,'CBA','Cow','Owl'])
string

0       A
1       C
2       D
3     Aaa
4    BaCa
5     NaN
6     CBA
7     Cow
8     Owl
dtype: object

In [115]:
string.str.lower()

0       a
1       c
2       d
3     aaa
4    baca
5     NaN
6     cba
7     cow
8     owl
dtype: object

In [116]:
string.str.upper()

0       A
1       C
2       D
3     AAA
4    BACA
5     NaN
6     CBA
7     COW
8     OWL
dtype: object

# operations for dataframe missing values 

In [120]:
df4=df3.copy()
df4

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [121]:
df4.fillna(4)


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  4.0       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  4.0       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [122]:
meanAge=df4['age'].mean()
df4['age'].fillna(meanAge)

a    2.500
b    3.000
c    0.500
d    3.375
e    5.000
f    1.500
g    4.500
h    3.375
i    7.000
j    3.000
Name: age, dtype: float64

In [123]:
df5=df3.copy()
df5

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [124]:
#احذف اي صف فيه خانه فاضية
df5.dropna(how='any')

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no